### ISSUE TITLE
"method handler crashed" in v1.5.0

### ISSUE THREAD

**Issue by rykawagu** [microsoft/vscode-azure-blockchain-ethereum#58] opened 2020-07-20 09:10 UTC
### environment
vscode-azure-blockchain-ethereum v1.5.0
VSCode: 1.47.2

### Symptom
After building and deploying a sample smart contract (HelloBlockchain.sol) to Azure Blockchain Service, unable to send transaction via Smartcontract interation Page, which can be accessed from [Show Smart contract Interation Page].

seems like there was same issue that VSCode said same error content. but same symptom was reproduced in v1.5.0 as well.
in v1.5.0, in my understanding the plugin supports smart contract intraction page for contracts deployed to ABS.

Prev Issue(Closed): https://github.com/microsoft/vscode-azure-blockchain-ethereum/issues/52

all the steps I tried are based from https://docs.microsoft.com/en-us/azure/blockchain/service/send-transaction

![image](https://user-images.githubusercontent.com/42409300/87920641-74c1bf80-cab4-11ea-9875-74797df4c68c.png)

**Comment by caleteeter** [comment] 2020-07-20 12:44
hi @rykawagu, there are a few things here that seems to be mixed.

* No version of the extension support Smart Contract Interaction with remote contracts (including ABS).  This will only work for locally deployed contracts.
* Method handler crashed was caused by a breaking change that came with an upgrade to Azure Blockchain Service a few weeks back.  Version 1.5.0 fixed this issue.  What this does mean is that if you had an previously deployed version of ABS, you will need to recreate this.

We continue to have trouble supporting the Smart Contract Interaction page, and I have another issue open to track this (#57).  I am starting to question whether we should rethink this approach.  What we initially were targeting was to build some react based components that could be used inside the IDE and then we can also have these available for use outside the IDE.  Sounded good, but supporting the react app inside the IDE requires some IPC magic that hides too much of what is going on.  This is evident by the number of issues surrounding this component.  We have asked for have this interaction component upgraded to support more types so it seems there is interest from user that they will use this component.

I am thinking of 2 options:

* Remove smart contract interaction from the IDE, and make it a standalone component that can be used with your deployed contracts (local or remote).
* Change the Smart contract interaction to be IDE native, possibly removing react dependency and use the native UI in VS Code for collecting parameters, submitting transactions, etc.

Interested in your feedback on either of these approaches or others you have thought of?

**Comment by JYeop** [comment] 2020-07-29 06:03
Same problem here...

**Comment by caleteeter** [comment] 2020-08-02 13:19
The method handler crash is part of the some upgrades that were done with ABS and requires a redeployment of a new ABS instance and v1.5.0 to fix.  I am working on a fix for smart contract interaction as well in #57 .  Closing this issue but feel free to reopen if you have an persistent issues with deployments to ABS.

**Closed by caleteeter** 2020-08-02 13:19 UTC
Labels: investigating
