### ISSUE TITLE
RPC error when writing data to smart contract in ABS

### ISSUE THREAD

**Issue by rpajunen** [microsoft/vscode-azure-blockchain-ethereum#56] opened 2020-07-02 13:24 UTC
I have encountered an issue when following the tutorial (https://docs.microsoft.com/en-gb/azure/blockchain/service/ethereum-logic-app#generate-a-workflow) to use VS Code to generate logic app workflow for REST based micro-service.

I’m using the HelloBlockchain.sol smart contract that is deployed to ABS. I am able to use the generated logic app to read data from the smart contract (property.requestMessage) but when I try to write data (function.sendRequest) I get the following error message in the logic app:

```json
{     
  "status": 400,
  "message": "Encountered RPC error when establishing communicating with the blockchain network -32000: method handler crashed\r\nclientRequestId: f6ffae1b-899e-404b-9113-37d2249b3a9b",
  "error": {
    "message": "Encountered RPC error when establishing communicating with the blockchain network -32000: method handler crashed"
  },
  "source": "blockchainethereum-we.azconn-we-01.p.azurewebsites.net"
}
```

I’ve tried using private key and account address & account password in the connection, two different smart contracts as well as using GET instead of POST with hardcoded data but the the error still persist.

**Comment by caleteeter** [comment] 2020-07-02 13:58
Checking the code generators for apps to see if the gas limit issue affects them.

**Comment by caleteeter** [comment] 2020-07-02 15:59
This is related to the other issue we had with issue #54 .  The issue is a gas estimation issue.  We could update the logic app generated to include these gas parameters possibly.  To unblock you, you can add 2 parameters to the logic app, which will provide a high gas limit and 0 gas price.

![image](https://user-images.githubusercontent.com/8452367/86381500-6aea3080-bc5b-11ea-815a-8309a965389b.png)

**Comment by rpajunen** [comment] 2020-07-03 05:46
Thanks @caleteeter for the quick response. Adding the two parameter works, cheers!

**Comment by caleteeter** [comment] 2020-07-03 12:32
I am going to close this one, I have this noted in our backlog.

**Closed by caleteeter** 2020-07-03 12:32 UTC
