### ISSUE TITLE
Required apps

### ISSUE THREAD

**Issue by boteny02** [microsoft/vscode-azure-blockchain-ethereum#53] opened 2020-06-15 21:56 UTC
I had issue after all the requirement were met, the below disallowed my from using the extension as indicated below.
I sincerely need here
![image](https://user-images.githubusercontent.com/56955434/84709965-28d2a680-af5b-11ea-8534-15e1234b880d.png)

**Comment by caleteeter** [comment] 2020-06-15 22:02
Sure, this is typically caused by this:

1) For GIT - You will need to add a path the git bin folder.  The default location is C:\Program Files\Git\bin.  Add this folder to your system path variable.  Details [here](https://github.com/microsoft/vscode-azure-blockchain-ethereum/wiki/FAQ#Q-i-have-installed-the-extension-and-get-prompted-that-Git-client-is-not-installed-however-it-is-installed)

2) For Python - Similar deal here, except you can add this your path when installing Python.  The details are in our FAQ as well [here](https://github.com/microsoft/vscode-azure-blockchain-ethereum/wiki/FAQ#Q:-i-installed-all-of-the-pre-requisite-software-but-I-still-get-the-missing-or-old-version-notification-for-python)

**Comment by jerryasher** [comment] 2020-06-26 09:03
I'm asking this as a noob to vscode... So I have the same problem, but I am doing all my dev in wsl2, and in fact the lower right corner of the status bar reminds me that this folder is a `Remote-WSL: Ubuntu`

![image](https://user-images.githubusercontent.com/666633/85840264-1291cb00-b751-11ea-810e-4e91f0c0e1f5.png)

So my question is, should these requirements, node, python, npm, be installed in Windows 10, or in WSL/Ubuntu?

Also, does it really need Python 2.7.15, node v10.15, or will Python 3.8 and node 12 or 14 be good enough.  (Python 2.7!?)

**Comment by caleteeter** [comment] 2020-06-26 19:59
@jerryasher if you are using remote-wsl you can install the prereqs there (in linux).  For node you can use 10 min, but feel free to run later versions (however we do recommend LTS versions).  For Python, unfortunatley, we need 2.7.x because of a dependency that we have with scrypt.js for the time being.

**Comment by caleteeter** [comment] 2020-07-03 12:33
Closing this for now, feel free to open if the problem persists.

**Closed by caleteeter** 2020-07-03 12:33 UTC
Labels: question
